import openai
import pandas as pd
import argparse
from prompts.prompts_icl import icl_short_en_1


def create_icl_ex(df):

    prompts = []

    for _, row in df.iterrows():
        statement = row["Statement"]
        gt_label = row["Ground-truth label"]

        prompt = f"Input: {statement}\nOutput: {gt_label}"
        prompts.append(prompt)

    # Joining all the prompts together
    full_prompt = "\n\n".join(prompts)

    return full_prompt


def icl(df1, df2, api_key, gpt_result_filename):

    # Add 'Estimation' Column
    df2["Estimation"] = ""

    client = openai.Client(api_key=api_key)

    model = "gpt-4"

    ignore = 0

    # Using enumerate to get an index (idx) and a value (statement) together
    for idx, statement in enumerate(df2["Statement"]):

        # Construct the full prompt
        full_prompt = create_icl_ex(df1)
        full_prompt += f"\n\nInput: {statement}"

        # Set up messages
        messages = icl_short_en_1
        messages[-1]["content"] += full_prompt

        response = openai.ChatCompletion.create(model=model, messages=messages)

        answer = response["choices"][0]["message"]["content"]
        df2["GPT-4 Output"].iloc[idx] = answer

    df2.to_excel(f"{gpt_result_filename}.xlsx", index=False)


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description="Estimate Symptom and Section with In-Context Learning method"
    )
    parser.add_argument(
        "--data",
        help="Data File After Label Extraction with Excel Format",
        required=True,
    )
    parser.add_argument(
        "--examplar",
        help="Examplar File for In-Context Learning with Excel Format",
        required=True,
    )
    parser.add_argument("--apikey", help="Your openai api key", required=True)
    parser.add_argument(
        "--result", help="Filename of the output generated by GPT", required=True
    )

    args = parser.parse_args()
    data_filename = args.data
    examplar_file = args.examplar
    api_key = args.apikey
    gpt_result_filename = args.result

    # in-context learning
    data = pd.read_excel(f"{data_filename}.xlsx")
    examplar = pd.read_excel(f"{examplar_file}.xlsx")
    icl(examplar, data, api_key, gpt_result_filename)
